### ISSUE TITLE
Error while mousing over UI

### ISSUE THREAD

**Issue by ezonius** [TheHologram/DSP_Mods#1]
Happened when i moused over the UI, not sure which part of the UI though. 

![image](https://user-images.githubusercontent.com/61872098/107891626-35f7c900-6f20-11eb-8a15-2a56d30b1f52.png)

**Comment by ezonius** [comment]
Seems to happend after I hide the UI with F9, then reopen it again and mouse over the Reload button

**Comment by TheHologram** [comment]
Thanks. Its not really an issue other than they disable auto-save and show that banner.  I run into it occassionally when reloading and trying to figure out what the issue is.  You can save/quit/load to clear it not that you should have to.

Normally this is an exception being thrown while generating the IMGUI and not finishing certain calls but I dont think there are ones here.  Its just drawing labels.  But maybe there is some call that is unsafe that triggers it.  Which version?  1.6?  

I wonder if its related to the thing that shows the username underneath or another call that seems innocuous but isnt.

I've actually seen it with other that have IMGUI in the game so not uncommon but would be nice to isolate it.  I'll use your hint to see if I can isolate it .

**Comment by TheHologram** [comment]
Did some research and apparently this happens more when mouse events are used in OnGUI which should be moved to OnUpdate.  I'll see what I can do but its hard to reproduce.

**Comment by TheHologram** [comment]
Found the issue.  It seems to be the toolip triggering the problem.  Disabling on the main window fixes the problem.  

Thanks for the F9 hint. I dont know that I would have found it otherwise as it was not reliably triggering for me otherwise.
